<template>
  <div class="slide">
    <h1 class="color-change-5x">Lecture 07</h1>
    <h2 class="color-change-5x">
      Animations
    </h2>
  </div>
</template>

<style scoped>
.color-change-5x {
  -webkit-animation: color-change-5x 6s linear infinite alternate both;
  animation: color-change-5x 6s linear infinite alternate both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-3-8 13:14:6
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation color-change-5x
 * ----------------------------------------
 */
@-webkit-keyframes color-change-5x {
  0% {
    color: #19dcea;
  }
  25% {
    color: #b22cff;
  }
  50% {
    color: #ea2222;
  }
  75% {
    color: #f5be10;
  }
  100% {
    color: #3bd80d;
  }
}
@keyframes color-change-5x {
  0% {
    color: #19dcea;
  }
  25% {
    color: #b22cff;
  }
  50% {
    color: #ea2222;
  }
  75% {
    color: #f5be10;
  }
  100% {
    color: #3bd80d;
  }
}
</style>
