<template>
  <div class="lecture">
    <Slide00 title="Assignment 3 - Common mistakes or things to improve" />
    <div class="slide">
      <hr />
      <h4>GitHub</h4>
      <h5>
        Removing autogenerated pull request by GirHub Classroom meant to be used
        by teacher for providing Feedback
      </h5>
      <p>
        In the context of GitHub Classroom, when you submit your code assignment
        or project, GitHub generates a "Pull Request" on your behalf. A Pull
        Request is a mechanism in Git that allows you to propose changes to a
        codebase. In this case, it is used to submit your work for review. The
        term "Feedback Pull Request" indicates that the Pull Request created by
        GitHub Classroom is specifically intended for providing feedback on your
        code. Once you have submitted your assignment, your instructor or a
        designated reviewer will review your code, provide comments,
        suggestions, and corrections directly within the Pull Request. The
        Feedback Pull Request allows for a structured and collaborative approach
        to code review, enabling a clear record of feedback and discussions
        related to your work. It helps facilitate the learning process and
        encourages improvement through constructive feedback.
      </p>
      <img
        class=""
        src="../../assets/images/Assignment03Feedback-FeedbackPR.png"
        alt="Example of Feedback PR generated by GitHub Classroom bot"
      />
      <h5>Lack of branches per feature</h5>
      <p>
        While it may seem unnecessary to create branches when you are the sole
        contributor, it is still beneficial for several reasons:
      </p>
      <ul>
        <li>
          Isolation of Features: By creating separate branches for each feature
          or task, you can isolate your changes. This allows you to work on
          different features independently without them interfering with each
          other. It helps maintain clarity and organization within your project.
        </li>
        <li>
          Code Stability: Working on a separate branch gives you the freedom to
          experiment and make changes without affecting the stability of the
          main branch (often called "main" or "master"). It provides a safety
          net, allowing you to easily switch back to a stable state if something
          goes wrong or if a feature needs to be temporarily put on hold.
        </li>
        <li>
          Version Control: Branches serve as a form of version control. Each
          branch represents a specific state of your codebase, capturing the
          progress and changes made for a particular feature. This makes it
          easier to track and manage your code history, enabling you to revert
          to previous states or merge specific features into the main branch
          when they are complete.
        </li>
        <li>
          Collaboration Potential: Even if you are currently working alone,
          creating branches per feature sets a good practice for future
          collaboration. If you ever decide to work with others or contribute to
          an open-source project, having feature branches will streamline the
          process, allowing for easier integration and reducing conflicts.
        </li>
      </ul>
      <p>
        By following this branching approach, you maintain a clean and organized
        codebase, making it easier to manage your work and collaborate
        effectively if the need arises.
      </p>
      <img
        class=""
        src="../../assets/images/Assignment03Feedback-FeedbackPR.png"
        alt="Example of Feedback PR generated by GitHub Classroom bot"
      />
      <h5>
        Pushing to repository / not deleting commented files (You ain't gonna
        need it)
      </h5>
      <p>
        Commented out code is intentionally deactivated and not meant to be
        executed. Pushing files with exclusively commented out code defeats the
        purpose of version control, which is to maintain a functional and
        executable codebase.
      </p>
      <img
        class=""
        src="../../assets/images/Assignment03Feedback-FeedbackPR.png"
        alt="Example of Feedback PR generated by GitHub Classroom bot"
      />
      <h5>Title of mistake</h5>
      <p>
        Paragraph
      </p>
      <img
        class=""
        src="../../assets/images/Assignment03Feedback-FeedbackPR.png"
        alt="Example of Feedback PR generated by GitHub Classroom bot"
      />
      Photo by
      <a
        href="https://unsplash.com/@en?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText"
        >Yen Tran</a
      >
      on
      <a
        href="https://unsplash.com/photos/tYzjYXrMd0g?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText"
        >Unsplash</a
      >
    </div>
    <div class="slide">
      <hr />
      <h4>CSS or SASS Variables</h4>
      <h5>Implementation of CSS or SASS Variables only for coloros</h5>
      <p>
        Here are some examples of use cases for CSS variables or Sass variables
        in terms of color, fonts, spacing, and other scenarios:
      </p>
      <h5>Colors:</h5>
      <ul>
        <li>
          Primary color: Use a variable like
          <strong><code>--primary-color</code></strong> to define the primary
          color of your website or application. This can be reused across
          different elements and easily updated if needed.
        </li>
        <li>
          Text color: Create a variable such as
          <strong><code>--text-color</code></strong> to define the default text
          color. This allows for consistent styling throughout your project.
        </li>
      </ul>

      <h5>Fonts:</h5>
      <ul>
        <li>
          Font family: Define a variable like
          <strong><code>--font-family</code></strong> to set the primary font
          family for your project. This ensures consistent typography across
          different elements.
        </li>
        <li>
          Font size: Use a variable such as
          <strong><code>--font-size</code></strong> to specify the base font
          size, which can be adjusted for different elements or breakpoints.
        </li>
      </ul>

      <h5>Spacing:</h5>
      <ul>
        <li>
          Margin and padding: Utilize variables like<strong>
            <code>--margin</code></strong
          >
          or <strong><code>--padding</code></strong> to set standard spacing
          values. This helps maintain consistency in the spacing between
          elements.
        </li>
        <li>
          Grid layout: Define variables such as
          <strong><code>--grid-gap</code></strong> or
          <strong><code>--column-width</code></strong> to control the spacing
          and width of grid-based layouts.
        </li>
      </ul>

      <h5>Breakpoints:</h5>
      <ul>
        <li>
          Media queries: Use variables like
          <strong><code>--breakpoint-small</code></strong> or
          <strong><code>--breakpoint-large</code></strong> to define breakpoints
          for responsive design. These variables can be used in media queries to
          adjust styles based on different screen sizes.
        </li>
      </ul>

      <h5>Animation and transition durations:</h5>
      <ul>
        <li>
          Animation duration: Set a variable like
          <strong><code>--animation-duration</code></strong> to specify the
          duration of animations throughout your project. This allows for easy
          adjustment and consistency.
        </li>
        <li>
          Transition duration: Use a variable such as
          <strong><code>--transition-duration</code></strong> to control the
          duration of CSS transitions, providing a consistent and adjustable
          transition experience.
        </li>
      </ul>

      <h5>Z-index:</h5>
      <ul>
        <li>
          Layering: Create variables like
          <strong><code>--z-index-top</code></strong> or
          <strong><code>--z-index-modal</code></strong> to manage the stacking
          order of elements. This helps ensure consistent and organized layering
          within your layout.
        </li>
      </ul>
      <p>
        Remember, these examples are not exhaustive, and you can use variables
        for various other aspects of your project, such as border styles,
        shadows, form styling, and more.
        <span class="action--highlight"
          >The goal is to identify values that are reused or subject to change
          and encapsulate them within variables for easy maintenance and
          flexibility.</span
        >
      </p>
    </div>
    <iframe
      height="900"
      style="width: 100%;"
      scrolling="no"
      title="Untitled"
      src="https://codepen.io/AniWeyn/embed/PoyewLJ?default-tab=css"
      frameborder="no"
      loading="lazy"
      allowtransparency="true"
      allowfullscreen="true"
    >
      See the Pen
      <a href="https://codepen.io/AniWeyn/pen/PoyewLJ"> Untitled</a> by Sabina
      Niewiadomska (<a href="https://codepen.io/AniWeyn">@AniWeyn</a>) on
      <a href="https://codepen.io">CodePen</a>.
    </iframe>
    <div class="slide">
      <hr />
      <h4>Title of category</h4>
      <h5>Title of mistake</h5>
      <p>
        Paragraph
      </p>
      <img
        class=""
        src="../../assets/images/Assignment03Feedback-FeedbackPR.png"
        alt="Example of Feedback PR generated by GitHub Classroom bot"
      />
      <a href="https://www.makeareadme.com/" target="_blank"
        >https://www.makeareadme.com/</a
      >
    </div>
  </div>
</template>

<script>
import Slide00 from "@/components/slides/title.vue";

export default {
  name: "Assignment02Feedback",
  components: {
    Slide00,
  },
};
</script>

<style>
img {
  width: 60vw;
}
</style>
